name: tests

on:
  push:
    branches: 
      - master
    paths:
      - '/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install && npm run test -- --coverage
